

input_length: 256
n_ant: 4

sampling:
  band:
    low: 0.08
    high: 0.23
  rate: 0.5
  filter:
    order_low: 5
    order_high: 10
    type: butter

training:
  batch_size: 32
  lengths:
    train: 5000
    unbiased: 1000000
  forward_skip_size: 200
  cdf: 0.7
  ns_readout_window: 800
  consecutive_deadtime: 2
  upsampling: 1
  start_frac: 0.3
  trigger_time: 200
  test_frac: 0.1
  val_frac: 0.1
  shift_signal_region_away_from_boundaries: False
  set_spurious_signal_to_zero: -1
  extra_gap_per_waveform: 0
  permute_for_RNN_input: False
  probabilistic_sampling_ensure_signal_region: False
  probabilistic_sampling_oversampling: 1.0