arch: Transformer
data_locations:
  base_folder: /mnt/md0/data/trigger-development/rno-g
  tag_folder_veff: CDF_0.7
  high_low_noise:   # For pre trigger data
    prod: prod_2023.03.24
  pre_trig_signal:  # For pre trigger data
    prod: prod_2023.05.16 


sampling:
  band:
    high: 0.23
    low: 0.08
  filter:
    order_high: 10
    order_low: 5
    type: butter
  rate: 0.5


training:
  batch_size: 64
  cdf: 0.7
  consecutive_deadtime: 2
  extra_gap_per_waveform: 200
  forward_skip_size: 199
  learning_rate: 0.0001
  ns_readout_window: 800
  permute_for_RNN_input: false
  probabilistic_sampling_ensure_min_signal_fraction: 0.3
  probabilistic_sampling_ensure_min_signal_num_bins: 3
  probabilistic_sampling_ensure_signal_region: true
  probabilistic_sampling_oversampling: 1.0
  randomize_batchitem_start_position: -1
  set_spurious_signal_to_zero: 100
  shift_signal_region_away_from_boundaries: true
  start_frac: 0.3
  test_frac: 0.1
  trigger_time: 200
  upsampling: 1
  val_frac: 0.1    

input_length: 128
n_ant: 4
